global:
  scrape_interval: 1s  # How frequently to scrape targets
  evaluation_interval: 1s  # How frequently to evaluate rules

scrape_configs:
  - job_name: 'backup-ro'  # Replace with your job name
    static_configs:
      - targets: ['192.168.100.23:9100']  # Replace with your application service name and port
  - job_name: 'snmp'
    static_configs:
      - targets:
        - 192.168.100.1:161  # IP address of the SNMP device
        - 192.168.100.3:161  # IP address of the SNMP device
    metrics_path: /snmp
    params:
      auth: [public_v2]
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116  # The SNMP exporter's address

